spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: jdbc:mysql://localhost:3306/test?&useSSL=false
    username: root
    password: 123456zxm

server:
  port: 9999
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml